################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
A_SRCS += \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libapp_trace.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libapp_update.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libasio.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libbootloader_support.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libbt.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libbtdm_app.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libc-psram-workaround.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libc.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libc_nano.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcoap.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcoexist.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libconsole.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcore.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcxx.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdetection.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdetection_cat_face.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdl.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdriver.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libefuse.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp-tls.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp32-camera.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp32.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_adc_cal.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_event.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_http_client.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_http_server.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_https_ota.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_https_server.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_ringbuf.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_websocket_client.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libespcoredump.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libespnow.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libethernet.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libexpat.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libface_detection.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libface_recognition.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfatfs.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfb_gfx.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfd.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfr.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfreemodbus.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfreertos.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libg-psram-workaround.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libhal.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libheap.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libimage_util.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libjsmn.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libjson.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/liblibsodium.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/liblog.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/liblwip.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libm-psram-workaround.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libm.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmbedtls.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmdns.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmesh.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmicro-ecc.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmqtt.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnet80211.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnewlib.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnghttp.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnvs_flash.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libod.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libopenssl.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libpe.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libphy.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libpp.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libprotobuf-c.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libprotocomm.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libpthread.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/librtc.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsdmmc.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsmartconfig.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsmartconfig_ack.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsoc.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libspi_flash.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libspiffs.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libtcp_transport.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libtcpip_adapter.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libulp.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libunity.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libvfs.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwear_levelling.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwifi_provisioning.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwpa.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwpa2.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwpa_supplicant.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwps.a \
../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libxtensa-debug-module.a 

A_SRCS__QUOTED += \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libapp_trace.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libapp_update.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libasio.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libbootloader_support.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libbt.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libbtdm_app.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libc-psram-workaround.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libc.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libc_nano.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcoap.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcoexist.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libconsole.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcore.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libcxx.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdetection.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdetection_cat_face.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdl.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libdriver.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libefuse.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp-tls.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp32-camera.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp32.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_adc_cal.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_event.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_http_client.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_http_server.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_https_ota.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_https_server.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_ringbuf.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libesp_websocket_client.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libespcoredump.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libespnow.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libethernet.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libexpat.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libface_detection.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libface_recognition.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfatfs.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfb_gfx.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfd.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfr.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfreemodbus.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libfreertos.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libg-psram-workaround.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libhal.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libheap.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libimage_util.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libjsmn.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libjson.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/liblibsodium.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/liblog.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/liblwip.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libm-psram-workaround.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libm.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmbedtls.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmdns.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmesh.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmicro-ecc.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libmqtt.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnet80211.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnewlib.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnghttp.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libnvs_flash.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libod.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libopenssl.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libpe.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libphy.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libpp.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libprotobuf-c.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libprotocomm.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libpthread.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/librtc.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsdmmc.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsmartconfig.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsmartconfig_ack.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libsoc.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libspi_flash.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libspiffs.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libtcp_transport.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libtcpip_adapter.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libulp.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libunity.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libvfs.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwear_levelling.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwifi_provisioning.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwpa.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwpa2.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwpa_supplicant.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libwps.a" \
"../arduino_lib/framework-arduinoespressif32/tools/sdk/lib/libxtensa-debug-module.a" 


